config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :products
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  # belongs_to :user
  has_many :ingredients, inverse_of: :product
  has_many :ingredients, dependent: :destroy
  has_one_attached :photo
  has_rich_text :content

  enum category: { "Short Drink": 0, "Long Drink": 1, "Aperitivos": 2, "Digestivos": 3 }
  enum subcategory: { "Sin Licor": 0, "Cerveza": 1, "Vino": 2, "Vodka": 3, "Ron": 4, "Tequila": 5, "Whisky": 6, "Coñac": 7, "Ginebra": 8, "Sidra": 9, "Pisco": 10, "Brandi": 11 }

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

  validates :name, :photo, :category, :recipe, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.ingredients.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    @product.save

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity, alert: "Por favor verificar campos vacíos" }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product) }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :category, :content, :recipe, :price, :status, :subcategory, :user_id, :photo, ingredients_attributes: [:id, :name, :_destroy] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/ingredients/_form.html.erb
<%= simple_form_for(@ingredient) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id ingredient %>">
  <p>
    <strong>Name:</strong>
    <%= ingredient.name %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= ingredient.product_id %>
  </p>

</div>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Show this ingredient", @ingredient %> |
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

app/views/ingredients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ingredients</h1>

<div id="ingredients">
  <% @ingredients.each do |ingredient| %>
    <%= render ingredient %>
    <p>
      <%= link_to "Show this ingredient", ingredient %>
    </p>
  <% end %>
</div>

<%= link_to "New ingredient", new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

app/views/ingredients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ingredient %>

<div>
  <%= link_to "Edit this ingredient", edit_ingredient_path(@ingredient) %> |
  <%= link_to "Back to ingredients", ingredients_path %>

  <%= button_to "Destroy this ingredient", @ingredient, method: :delete %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocktailsell</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag "favicon.png", rel: "icon", type: "image/png" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Codystar&family=Montserrat&family=Pacifico&display=swap" rel="stylesheet">

  </head>

  <body><%= render "shared/navbar" %>


<%= render "shared/flashes" %>

    <%= yield %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="autoNumeric.min.js" type="text/javascript"></script>
  </body>
</html>

app/views/pages/home.html.erb
    <div class="container">

      <hr class="border border-info">

      <img class="b" src="assets/shot-bg.png" style="position: absolute" alt="">
      <%# <img class="c" src="assets/palmera-1.png" style="position: absolute" alt=""> %>

        <!-- carrusel principal -->

      <div id="carouselExampleDark" class="carousel carousel-dark slide mb-5"  data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner" >
          <div class="bg-carrusel">

          </div>


          <div class="carousel-item active" data-bs-interval="10000">
            <div class="carousel-caption d-none d-md-block">
              <div class="row align-items-center">
                <div class="col-6 align-center neons">
                  <h1><em> CocktailSell</em></h1>
                  <p class="text-light text-primary fs-3 sub-title-c">Un cocktail para cada ocasión</p>
                </div>
                <div class="col-6">
                  <img class="rounded-1" src="/assets/coctel-1.png" style="max-height: 350px;"  alt="">
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item" data-bs-interval="2000">
            <div class="carousel-caption d-none d-md-block">
              <div class="row align-items-center">
                <div class="col-6 align-center neons neon">
                  <h1><em> CocktailSell</em></h1>
                  <p class="text-light fs-3 sub-title-c">Mezcla de sabores y emociones</p>
                </div>
                <div class="col-6 align-center">
                  <img class="rounded-1" src="assets/corona.png" style="max-height: 350px;"  alt="">
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="carousel-caption d-none d-md-block">
              <div class="row align-items-center neons">
                <div class="col-6">
                   <h1><em> CocktailSell</em></h1>
                  <p class="text-light fs-3 sub-title-c">Para todos los gustos!</p>
                </div>
                <div class="col-6">
                  <img class="rounded-1" src="assets/wine.png" style="max-height: 380px;"  alt="">
                </div>
              </div>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
          <span class="carousel-control-prev-icon bg-success rounded-circle p-2" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
          <span class="carousel-control-next-icon bg-success rounded-circle p-2" aria-hidden="true"></span>
          <span class="visually-hidden ">Next</span>
        </button>
      </div>

      <!-- descripcion -->
      <div class="row">
        <figure class="text-center my-5">
          <blockquote class="blockquote">
            <p class="text-light">Cada cocktail es una historia que se sirve de forma innovadora</p>
          </blockquote>
          <figcaption class="blockquote-footer">
            Déjate <cite title="Source Title"></cite>envolver por <cite title="Source Title">Nuestra magia</cite>
          </figcaption>
        </figure>
      </div>

      <div class="text-center">
       <!-- <span class="d-flex justify-content-center"> <button type="button" href="/products" class="btn btn-info  ps-5 pe-5 rounded-pill">Info</button> </span> -->
       <%= link_to 'Ver Productos', products_path, class:"btn btn-primary rounded-5 px-3 button button-1" %>
      </div>

 <!-- cards de productos -->

     <hr>

<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-3">
        <% @products.each do |product| %>
              <%= render partial: 'products/product', object: product %>
          <% end %>
    </div>
  </div>

      <!-- descripcion 2 -->
      <div class="row">
        <figure class="text-center my-5">
          <blockquote class="blockquote">
            <p class="text-light">Combinánamos a la perfección la experiencia y sabor de los mejores cocktails </p>
          </blockquote>
          <figcaption class="blockquote-footer">
            Un ambiente <cite title="Source Title">Cualquier ocasión</cite>
          </figcaption>
        </figure>
      </div>

      <div class="text-center mx-3">
        <%= link_to 'Ver Productos', products_path, class:"btn btn-primary rounded-5 px-3 button button-1" %>
      </div>


       <!-- Formulario de contacto -->


    <div class="row background-1 mt-5 pb-5 justify-content-center">
        <a name="contact" id="contact"></a>
      <h3 class="text-center mt-5 text-light"> <strong> CONTÁCTANOS </strong></h3>
      <div class="row align-items-center justify-content-center mt-4">
        <div class="col-md-12 col-lg-4">
            <div class="d-flex justify-content-center icons mt-3 mv-3">
                <a target="_blank" href=""><i class="pe-4 fs-1 fa-brands fa-facebook text-info"></i></a>
                <a target="_blank" href=""><i class="pe-4 fs-1 fa-brands fa-whatsapp text-info"></i></a>
                <a target="_blank" href=""><i class="pe-4 fs-1 fa-brands fa-instagram text-info"></i></a>
          </div>
          <div class="row icons mt-3 justify-content-center">
              <p class="text-center text-light"><i class="fa-solid fa-envelope-open-text"></i> <span class="ps-2"> cocktailsell@gmail.com </span></p>
              <p class="text-center text-light"><i class="fa-solid fa-location-dot"></i> <span class="ps-2"> Medellin - Antioquia </span></p>
          </div>


        </div>
        <div class="col-md-12 col-lg-4 d-flex justify-content-center">
          <%= link_to "#", class: "navbar-brand" do %>
          <img src="assets/favicon.png" alt="" style="height: 150px; width: 150px;"  class="p-0 m-0">
          <% end %>
        </div>
        <div class="col-md-12 col-lg-4 py-5 m-0 container-03">
          <form target="_blank" action="https://formsubmit.co/8ce1e40cedabffb63ce31436c8660067" method="POST">
            <input type="hidden" name="_next" value="http://localhost:3000/">
            <input type="hidden" name="_captcha" value="false">
            <div class="form-group">
              <div class="form-row">
                <div class="col">
                  <input type="text" name="name" class="form-control" placeholder="Full Name" required>
                </div>
                <div class="col">
                  <input type="email" name="email" class="form-control" placeholder="Email Address" required>
                </div>
              </div>
            </div>
            <div class="form-group">
              <textarea placeholder="Your Message" class="form-control" name="message" rows="4" required></textarea>
            </div>
           <span class="d-flex justify-content-end"> <button type="submit" class="btn btn-lg btn-primary ps-5 pe-5 mb-3 mt-3 text-center"> <span class="pe-2 fs-6"> Send Message  </span> <i class="pt-1 opacity-75 fa-solid fa-paper-plane"></i> </button> </span>
          </form>
        </div>

        <!-- fin formulario -->

        <!-- <img class="b" src="assets/harina5.png" style="position: absolute" alt=""> -->


    </div>   <!-- cierra container -->

app/views/products/_ingredient_fields.html.erb
<%= content_tag :div, class: "nested-fields", data: { new_record: f.object.new_record? } do %>
  <div class="row align-items-center justify-content-center">
    <div class="col-8 mb-3">
      <!-- <%= f.label :"Ingrediente:" %> -->
      <%= f.text_field :name, class: 'form-control', placeholder: "Ingrese Nombre de ingrediente" %>
    </div>
    <div class="col-3">
      <%= link_to "#", data: { action: "click->nested-form#remove_association" } do %>
            <i class="fa-solid fa-trash-can fs-4"></i>
            <%= f.hidden_field :_destroy %>
          <% end %>
      <% end %>
    </div>
  </div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <div class="card mb-3 card-all-product">
    <div class="row g-0">
      <div class="col-lg-4  d-flex align-items-center justify-content-center text-center" >
          <% if product.photo.attached?  %>
          <%= cl_image_tag product.photo.key,  height: 100, width: 100, crop: :fill, class:"rounded-4" %>
          <% else %>
        <img src="assets/copa-rosa.png" class="img-fluid rounded-start" alt="IMAGEN">
         <% end %>
      </div>
      <div class="col-lg-8">
        <div class="card-body">
          <h5 class="card-title"><%= link_to product_path(product), class: "text-decoration-none fw-bold text-info" do %>
          <h5 class="mt-3 "><%= (product.name).capitalize %></h5>
         <% end %>
         <span class="badge rounded-pill bg-dark fw-lighter"><%= product.category %></span>
            <span class="badge rounded-pill bg-dark fw-lighter"><%= product.subcategory %></span>
          <p class="card-text fs-6 pt-5 d-flex justify-content-end me-5"><%= number_to_currency(product.price) %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/_product_show.html.erb
<div class="container">
  <section class="row justify-content-center">
    <div class="col-lg-10">
      <div class="card mb-3 bg-show-product">
        <div class="row g-0 rounded-4 ">
          <div class="col-lg-5  d-flex align-items-center justify-content-center img-card-1" >
              <% if @product.photo.attached?  %>
              <%= cl_image_tag @product.photo.key, height: 300, width: 280, crop: :fill, class:"r-img" %>
              <% else %>
            <img src="../assets/copa-rosa.png" class="img-fluid rounded-start" alt="IMAGEN", style="width: 200px;" >
            <% end %>
          </div>
          <div class="col-lg-7 ">
            <div class="card-body">
              <h5 class="card-title"><%= link_to product_path(@product), class: "text-decoration-none fw-bold text-info" do %>
              <h5 class="mt-3 fs-1 text-primary"><%= (@product.name).capitalize %></h5>
            <% end %>
              <% if @product.status %>
                <div class="row">
                  <div class="col">
                    <p class="text-success fs-6">Producto Disponible</p>
                  </div>
                  <% else %>
                  <div class="col">
                    <p class="text-warning fs-6">Producto No Disponible</p>
                  </div>
                <% end %>
              </div>

            <span class="badge rounded-pill bg-dark"><%= @product.category %></span>
                <span class="badge rounded-pill bg-dark"><%= @product.subcategory %></span>
                <p class="card-text fs-5  d-flex justify-content-end me-5"><%= number_to_currency(@product.price) %></p>
                <div class="scroll-card mt-0 pt-0 font-recipe">
                  <tr>
                      <td> <h4 class="text-light fs-5"> <strong> Ingredientes:</strong></h4>
                        <% @product.ingredients.all.each do |p|%>
                        <ul class="list-group">
                          <li class="list-group-item bg-transparent text-light border-0"><i class="fa-solid fa-martini-glass-citrus"></i> <span class="mx-3"><%= p.name %></span></li>
                        </ul>
                        <% end %>
                      </td>
                    <td> <h4 class="text-light fs-5"> <strong> Recipe: </strong></h4> </td>
                      <td> <%= simple_format(@product.recipe) %> </td>
                  </tr>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="row justify-content-center">
    <div class="col-lg-10">
                <div class="row justify-content-end">
                  <% if current_user %>
                  <div class="col-lg-2 text-end">

                      <%= link_to products_path, class: "text-decoration-none link-dark", data: { turbo_method: :delete, controller: 'sweetalert', action: "click->sweetalert#show", sweetalert_title_value: @product.name } do %>
                      <i class="fa-solid fa-trash-can rounded-5 p-2 bg-warning"></i>
                         <% end %>


                    <%= link_to edit_product_path(@product), class: "text-decoration-none link-dark circle-icon" do %>
                    <i class="fa-solid fa-pen-to-square rounded-5 p-2 bg-info"></i>
                        <% end %>
                          </div>
                     <% end %>

      </div>
  </section>
</div>

app/views/products/edit.html.erb
<%= render "form", product: @product %>

app/views/products/index.html.erb
<div class="w-full">
  <div class="row ">
    <div class="col back-btn mb-0 mt-3 pb-0 ms-5">
    <%= link_to  :back do%>
        <i class="fa-solid fa-circle-arrow-left  text-info fs-3 " class="back-btn rounded-4" data-bs-toggle="tooltip" data-bs-placement="top" title="Go Back"></i>
    <% end %>
    </div>
    <div class="col back-btn mb-0 mt-3 pb-0 me-5 d-flex justify-content-end">
      <%= link_to  new_product_path do%>
          <i class="fa-solid fa-plus text-info fs-3" class="back-btn rounded-4" data-bs-toggle="tooltip" data-bs-placement="top" title="Agregar Nuevo Producto"></i>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center mt-1">
    <div class="col d-flex justify-content-center">
      <img class="" src="assets/limon-2.png" alt="" style="width: 80px;">
    </div>
    <div class="col d-flex align-items-center text-center">
        <div class="neon-2"> <h1> Nuestros Productos</h1></div>
      <%# <h4 class="fs-2 text-primary text-center align-bottom"> <strong> Nuestros Productos</strong></h4> %>
    </div>
    <div class="col d-flex justify-content-center">
      <img class="" src="assets/limon-2.png" alt="" style="height: 100px;">
    </div>
  </div>

<!-- cards de productos -->

  <div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-3">
        <% @products.each do |product| %>
              <%= render partial: 'product', object: product %>
          <% end %>
    </div>
  </div>

</div>

app/views/products/new.html.erb
<%# <h1>New product</h1> %>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
  <div class="row back-btn mb-0 mt-3 pb-0 ms-5">
    <%= link_to  :back do%>
        <i class="fa-solid fa-circle-arrow-left  text-info fs-3 " class="back-btn rounded-4" data-bs-toggle="tooltip" data-bs-placement="top" title="Go Back"></i>
    <% end %>
  </div>

  <p style="color: green"><%= notice %></p>

  <div class="" data-controller="">
                <%= render partial: 'product_show', object: @product %>
  </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div> -->
<div class="navbar navbar-expand-sm navbar-dark bg-glass navbar-lewagon">
  <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
     <ul class="navbar-nav">
   <!-- <%= link_to "/", class: "" do %>
      <%= cl_image_tag("https://res.cloudinary.com/dgktx5c4x/image/upload/v1677259144/gracialogo-removebg-preview_kvabbj.png",
                        width: 70, height: 70, crop: :fill) %>
    <% end %> -->
    <%= link_to "/", class: "" do %>
    <div class="neon-2 fs-1">CocktailSell</div>
    <% end %>
    <!-- <img src="assets/favicon.png" alt="" style="height: 60px; width: 60px;"  class="p-0 m-0"> -->
  </ul>

      <ul class="navbar-nav collapse navbar-collapse">
        <li class="nav-item">
        <!-- <%= link_to "CONTÁCTO", "#contact", class: "nav-link" %> -->
      </li>
      </ul>

    <ul class="navbar-nav collapse navbar-collapse">
      <li class="nav-item">
        <%= link_to "#", class: "nav-link" do %>
         <i class="fa-brands fa-whatsapp text-primary link-light fs-3"></i>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to "", class: "nav-link" do %>
          <i class="fa-brands fa-instagram text-primary link-light fs-3"></i>
        <% end %>
      </li>
    </ul>



    <div class="navbar-nav">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/duc3wvxve/image/upload/v1677856873/avatar_ec74ma.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end rounded-4 p-2" aria-labelledby="navbarDropdown">
              <%= link_to products_path, class: "dropdown-item" do %>
                <i class="fa-solid fa-cart-shopping"></i>
                <span class="ms-3">Productos</span>
                <% end %>
              <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" do %>
              <i class="fa-solid fa-right-from-bracket"></i>
              <span class="ms-3"> Salir </span>
              <% end %>
            </div>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link" do %>
              <i class="fa-solid fa-circle-user fs-2"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>